name: tailscale-derper-http

services:
  derper:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    volumes:
      - type: volume
        source: var-run-tailscale
        target: /var/run/tailscale
      - type: volume
        source: var-lib-tailscale
        target: /var/lib/tailscale
      - type: bind
        source: ${DERP_SERVER_CERT_SOURCE_DIR}
        target: ${DERP_SERVER_CERT_TARGET_DIR}
    ports:
      - 443:443/tcp
      - 3478:3478/udp
    command:
      - "derper"
      - "--a=:443"
      - "--verify-clients=true"
      - "--hostname=${DERP_SERVER_HOSTNAME}"
      - "--http-port=-1"
      - "--certdir=${DERP_SERVER_CERTIFICATE_TARGET_DIR}"
    restart: always
  tailscale:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    volumes:
      - type: volume
        source: var-run-tailscale
        target: /var/run/tailscale
    environment:
      - TS_HOSTNAME=${TAILSCALE_HOSTNAME}
      - TS_SOCKET=/var/run/tailscale/tailscaled.sock
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_AUTH_ONCE=true
    restart: always
volumes:
  var-run-tailscale:
  var-lib-tailscale:
