name: tailscale-derper-https

services:
  derper:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    volumes:
      - type: volume
        source: var-run-tailscale
        target: /var/run/tailscale
      - type: volume
        source: var-lib-tailscale
        target: /var/lib/tailscale
    secrets:
      - source: derper-tls-cert
        target: /run/secrets/${DERP_SERVER_HOSTNAME}.crt
      - source: derper-tls-key
        target: /run/secrets/${DERP_SERVER_HOSTNAME}.key
    ports:
      - 8080:443/tcp
      - 3478:3478/udp
    command:
      - "derper"
      - "--a=:443"
      - "--verify-clients=true"
      - "--hostname=${DERP_SERVER_HOSTNAME}"
      - "--http-port=-1"
      - "--certmode=manual"
      - "--certdir=/run/secrets"
    restart: always
  tailscale:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    volumes:
      - type: volume
        source: var-run-tailscale
        target: /var/run/tailscale
    environment:
      - "TS_HOSTNAME=${TAILSCALE_HOSTNAME}"
      - "TS_SOCKET=/var/run/tailscale/tailscaled.sock"
      - "TS_STATE_DIR=/var/lib/tailscale"
      - "TS_AUTH_ONCE=true"
    restart: always
volumes:
  var-run-tailscale:
  var-lib-tailscale:
secrets:
  derper-tls-crt:
    file: ${DERP_SERVER_CERT_SOURCE_PATH}
  derper-tls-key:
    file: ${DERP_SERVER_KEY_SOURCE_PATH}
