name: Build Docker Image for Tailscale (including DERP)
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: "Version of Tailscale, e.g., v1.74.1"

env:
  tailscale_upstream_repo: tailscale/tailscale
  tailscale_source_path: tailscale
  build_repo_path: tailscale-build
  docker_image_name: tailscale

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out build repo
        with:
          path: ${{ env.build_repo_path }}
      - name: Check out Tailscale Source Code
        uses: actions/checkout@v4
        with:
          repository: ${{ env.tailscale_upstream_repo }}
          ref: ${{ github.event.inputs.version }}
          path: ${{ env.tailscale_source_path }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Apply patch
        run: |
          cd ${{ GITHUB_WORKSPACE }}/${{ env.tailscale_source_path }}
          git apply ${{ GITHUB_WORKSPACE }}/${{ env.build_repo_path }}/patches/*.patch
      - name: Build for linux/amd64, and push
        run: |
          cd ${{ GITHUB_WORKSPACE }}/${{ env.tailscale_source_path }}
          GOOS=linux GOARCH=amd64 PUSH=true \
            REPOS=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.docker_image_name }} \
            ./build_docker.sh
      - name: Build for linux/arm64, and push
        run: |
          cd ${{ GITHUB_WORKSPACE }}/${{ env.tailscale_source_path }}
          GOOS=linux GOARCH=arm64 PUSH=true \
            REPOS=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.docker_image_name }} \
            ./build_docker.sh
